### ISSUE TITLE
Save users email addresses

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#190]

**Comment by kelseyah** [comment]
https://developers.facebook.com/docs/facebook-login/permissions/#reference-email

**Comment by jayres** [comment]
Hmm.... 

The email is not coming down by default for my user. Can we have someone else check to see if the payload from FB has the email address?

Here is the data coming from Facebook from my account:

`{ sender: { id: 'xx' },
  recipient: { id: 'xx' },
  timestamp: xx,
  message: { mid: 'mid.xx:xx', seq: xx, text: 'hi' } }
{ first_name: 'xx',
  last_name: 'xx',
  profile_pic: 'xx',
  locale: 'en_US',
  timezone: -4,
  gender: 'xx' }`

**Comment by jayres** [comment]
https://developers.facebook.com/docs/messenger-platform/user-profile

**Comment by jayres** [comment]
https://developers.facebook.com/docs/messenger-platform/account-linking

**Comment by oshoham** [comment]
http://espeo.eu/blog/user-permissions-messenger-bots/

**Comment by jayres** [comment]
Facebook's API has the email field but Messenger's doesn't. This means that we would have to have an auth flow into Facebook to get the info.

This process is outlined in Oren's link above and I am sure this would work... From the article:

`Currently we have two solutions. Both are created with user redirections to a specific url. Our first solution refers to redirecting the user only from your server, the second redirects from FB and your server.`

Basically we will need to use a login form on our application which has the user log in on Facebook and then redirects them back to messenger. This would be a pretty big step in the signup flow though we would have access to more information. Oren definitely posted the correct tutorial link if we need to get information from a user other than the limited scope from messenger. 

My suggestion would be to forego this for now since it will breakup the user flow and use a message prompt in a future version (which will also allow users to opt out immediately...).

**Comment by kelseyah** [comment]
yea let's not do that. we can do a email capture campaign later if we need it
