### ISSUE TITLE
Feedback for what happens after onboarding

### ISSUE THREAD

**Issue by JoshData** [CallParty/CallParty#205]
I got my first message about a campaign! So cool. Just some feedback:

First, I use Messenger via Facebook.com on my computer. Because the message is segmented, the first thing I see is:

![screenshot from 2017-03-15 12-28-58](https://cloud.githubusercontent.com/assets/445875/23959404/80680bee-097b-11e7-813c-e142b9362db9.png)

Just the last message, which is a little confusing. I'm just pasting that as an fyi. I don't think there's a fix here.

> Great! You'll be calling 2 Congress Members.
(and later in the script)
> Do you want to try your next Congress Member?

Probably lowercase "members". It's formally "Members of Congress" but no one writes it "Congress Members".

> "I'd like the Congress Member

Would be really good to tailor this to whether you are calling a representative or senator and use those terms. It'll sound very scripted to the person answering the phone if you say "the Congress Member." Saying "Representative [Lastname]" or "Senator [Lastname]" would be ideal.

> to oppose the bill, because

Comma! If nothing else I will always point out extraneous commas. :)

The rest of the script is _very_ good. Love the link to teenvogue. Great touch.

**Comment by jayres** [comment]
1. I sort of like the "Are you ready to call?" prompt because it gives an action in the message instead of a clipped portion of the issue itself. Thoughts?
2. @kelseyah - Should I change it to say from Congress Member to Member of Congress? I think it makes sense and would like to keep the language consistent with other sources. I think we can also make it say "my Senator" or "my Representative" too which would probably be better overall. Perhaps avoid the specific name of the MOC to avoid a lookup at the application side and also because there may be more than one call. We can do it either way though.

3. the "oppose the bill, because" comment is good - but that's specific so we can get it right on the next message :-)

**Comment by kelseyah** [comment]
@jayres I'm cool with the message preview – most folks are viewing these on their phones which is a bit different experience. either way everyone's right in that there's not much of a fix to be had.

I'm updating now in kelsey/convo-updates so every instance is "Member(s) of Congress" or just "member" and fixed the weirdness in the multi-rep case. 

thx for all the notes @JoshData! me and andrew over-comma sometimes :) glad you liked the script!
