### ISSUE TITLE
Change 'Update' to 'Message'

### ISSUE THREAD

**Issue by mhfowler** [CallParty/CallParty#333]
When I make an update, the update is not going just to users who were participants in the campaign. I made a campaign with no actions and went straight to making an update (with no targeting), and all users are listed, and when I send, all users get the update. I think updates would make more sense if they only go to a) users who have received a prior message about the campaign, or better b) users who actually made a call on the campaign. (If they didn't make a call, they probably don't want to hear from CallParty again on the same subject.) Imagine that I send a campaign, then 1000 more users sign up, and then I send an update using borrowed targeting. The new 1000 users will get the update before they've been asked to make a call.
(It could be useful to send a blast to all users about updates to CallParty, but that probably shouldn't be the default.)

**Comment by mhfowler** [comment]
hmm
- if you do borrowed targeting, it will only send to users who received the action you are borrowing from 

if you want something to be an update which only goes to people who have received a particular thing, I think borrowed targeting makes sense 

if you want to choose your own targeting, it seems like a useful feature to me to also target new users

**Comment by mhfowler** [comment]
maybe we dont need code changes, but curious if there is a better way we could describe how this works and how to use it @kelseyah

**Comment by kelseyah** [comment]
The way it works right now is as intended and useful, there are essentially two scenarios:

1) An update that goes to a group of people that received a prior call to action uses borrowed or inherited targeting so that it goes to everyone who is contacted about that issue.

> (If they didn't make a call, they probably don't want to hear from CallParty again on the same subject.)

This isn't actually true – many people don't make a call because they're just busy, doesn't mean they're not interested in hearing about it. In fact I have a theory that many of our users stay users (despite not making calls) because they like getting information in a digestible way. So far it hasn't been problematic and no one has dropped due to these updates.

2) An update that goes to people whether it's everyone or a different segmentation. These are useful for a bunch of various reasons. 

Sooo like you said, doesn't really need to change from a functionality standpoint, but for clearer messaging we could just call it "Message" instead of update, since it sends a singular message. What do you think?

**Comment by JoshData** [comment]
I think the more important case is whether people who haven't yet been asked to make a call should receive the message. But, yeah, if you have a toggle between Update (only sends to people who have received an action) or Message (sends to anyone), it'll make more sense.
