### ISSUE TITLE
Add timing between messages so it's not cray

### ISSUE THREAD

**Issue by kelseyah** [CallParty/CallParty#74]

**Comment by jayres** [comment]
It looks like this isn't in the core Botkit functionality. I am into adding it as `setTimeout` in the js, where we give a 2-10 second delay between messages, but that is also not a great solution because the process is still running - it just waits. If there are a large amount of processes running at once, this would just make the duration of these processes longer and spend more RAM/CPU from the server.

Does anyone have additional thoughts about how/why to do this other than setTimeout?

**Comment by mhfowler** [comment]
I like setTimeout

**Comment by jayres** [comment]
Here is something that should work - but WHERE does it go is the question.

.then(() => setTimeout( function() {console.log('delay')}, 200) )

You can't attach it to the prototype object because the `botReply` function is itself a promise (so you'd have to make it a promise with a promise inside of it - which is actually fine but weird). 

Additionally, putting it in between different instances of the `botReply` function doesn't work (for some reason....)

Thoughts on this?

**Comment by kelseyah** [comment]
Just catching up – I'm going to move this to v1.1 if that's cool, splitting up the messages already helps a lot and it will be good to add this but probably not critical for v1

**Comment by oshoham** [comment]
If we want to use `setTimeout` in a promise chain, we can do by wrapping it in a promise, like so:

```
function delay(time) {
  return new Promise(function(resolve) {
    setTimeout(resolve, time)
  })
}

// promise chain example
botReply(user, 'hi').then(() => delay(1000)).then(() => botReply(user, 'a second has passed'))
```

**Comment by oshoham** [comment]
closing b/c the timing between messages seems fine for the time being
